---
language: python
services: docker

env:
  global:
    - ROLE_NAME: first5ssh
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test

# yamllint disable rule:line-length
notifications:
  slack:
    secure: wyYcAO3YU+nMp2i93OgsPQDP5aYmrZ6eiptqAkC8mLBHB6VhgfZLExN7KiBcvenBFsUqMaeWEgm71U84pUsOPrXltkObBBtlSAGhLacjycDpy44YDu/dTGE+PR4p2gf3/Xpp/XQOThdx22cRlsspptgYAi3064bGcuUoVMXjqAdP4qc9wnlExF86eynb+uD56/rXKYW3UB/49Nxf145NIjUdd8dgxN4d5+2+Y4mQRCWNbe94TefQvrgvj1EQV+WyLAi2GEfwHjF14rOowt5gPOY8bNmsM4qV3uIXJeTTXKldPA5OP7tCbbPnmQ2Mbv2/I/oTUoNpBfnAKgMLsXl431iQjFcfR5d6sB2rDxpizwdsIAouPmNlmWf+Clz6yjiBqJBMU6IQXBZQD3TE03Ypn2SAk8sjzt/s0mAYriBZOmqRSCIqyfWI/YF4eDO9sFWn/nxtrKH8nTh9YYGkbQsHFmVnze9RMkzUSrnsaSP8pR8CLdpvp9ClO/qcaYsje2wsJU5lkhiQBuUk4ZG5DmaVaAb/OVtIiiHUxv3+HsVptSacTMgN7l7B9YzCoYjFoIu0U9/iD6cb5YMSNIe5gKBep/9cOBwYfV/AcEjoFmQwfDbg58DzRNZ6QKSrzTYanJz7QxWb3dujB6CPCtuahN/oh49TOwxhb5zXTd9MjXeAsOI=
# yamllint enable rule:line-length
