---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Debug ssh_server_key_bits
  debug:
    var: "{{ ssh_server_key_bits }}"
    verbosity: 4


- name: Check Missing privilege separation directory
  stat:
    path: '/var/run/sshd'
  become: true
  register: runsshd_exist

- name: Create Missing privilege separation directory
  file:
    path: '/var/run/sshd'
    state: directory
    recurse: yes
    mode: 0755
  become: true
  when: not runsshd_exist.stat.exists | bool


- name: SSH Config | add sshd (daemon) config file
  template:
    src: sshd_config.j2
    dest: "{{ ssh_config_path }}/sshd_config"
    backup: yes
    validate: "/usr/sbin/{{ ssh_daemon }} -T -f %s"
  become: true
  notify: First5 SSH | restart ssh
  when: first5ssh_manageconfig | bool

- name: SSH Config | add ssh (client) config file
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config_path }}/ssh_config"
    backup: yes
  become: true
  notify: First5 SSH | restart ssh
  when: first5ssh_manageconfig | bool
