---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: msg="ssh_server_key_bits {{ ssh_server_key_bits }}"
  debug: var={{ ssh_server_key_bits }}

- name: SSH Config | add ssh config file
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config_path }}"
    backup: yes
    validate: "/usr/sbin/{{ ssh_daemon }} -T -f %s"
  sudo: true
  notify: First5 SSH | restart ssh
  when: first5ssh_manageconfig
