---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      skip: true


- name: Debug ssh_server_key_bits
  debug:
    var: "{{ ssh_server_key_bits }}"
    verbosity: 4


- name: Check Missing privilege separation directory
  stat:
    path: '/var/run/sshd'
  become: true
  register: runsshd_exist

- name: Create Missing privilege separation directory
  file:
    path: '/var/run/sshd'
    state: directory
    recurse: true
    mode: 0755
  become: true
  when: not runsshd_exist.stat.exists | bool


- block:
    - name: Make sure config.d dir exists
      file:
        path: "{{ ssh_config_path }}/sshd_config.d"
        state: directory
        owner: "root"
        group: "root"
        mode: 0755

    - name: Check if we have updated ssh_host_rsa_key recently
      stat:
        path: "/etc/ssh/ssh_host_rsa_key"
      register: stat_rsa_results

    - name: Check if we have updated ssh_host_ed25519_key recently
      stat:
        path: "/etc/ssh/ssh_host_ed25519_key"
      register: stat_ed25519_results          

    - name: Regenerate host RSA keys
      community.crypto.openssh_keypair:
        path: /etc/ssh/ssh_host_rsa_key
        size: 4096
        type: rsa
        force: True
      when: ((ansible_date_time.epoch|int - stat_rsa_results.stat.mtime) > (sshkey_regen_days * 60 * 60 * 24))
  

    - name: Regenerate host ed25519 keys
      community.crypto.openssh_keypair:
        path: /etc/ssh/ssh_host_ed25519_key
        size: 4096
        type: ed25519
        force: True
      when: ((ansible_date_time.epoch|int - stat_ed25519_results.stat.mtime) > (sshkey_regen_days * 60 * 60 * 24))


    - name: Disable SSH short moduli for DH
      shell: set -o pipefail |
        cp /etc/ssh/moduli /etc/ssh/moduli.bak &&
        awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe &&
        mv /etc/ssh/moduli.safe /etc/ssh/moduli   
      
    - name: Put up hardening file
      template:
        src: ssh-audit_hardening.conf.j2
        dest: "{{ ssh_config_path }}/sshd_config.d/ssh-audit_hardening.conf"
        backup: true
        validate: "/usr/sbin/{{ ssh_daemon }} -T -f %s"
      become: true
  
  when: first5ssh_hardenssh | bool
  notify: First5 SSH | restart ssh

- name: SSH Config | add sshd (daemon) config file
  template:
    src: sshd_config.j2
    dest: "{{ ssh_config_path }}/sshd_config"
    backup: true
    validate: "/usr/sbin/{{ ssh_daemon }} -T -f %s"
  become: true
  notify: First5 SSH | restart ssh
  when: first5ssh_manageconfig | bool

- name: SSH Config | add ssh (client) config file
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config_path }}/ssh_config"
    backup: true
  become: true
  notify: First5 SSH | restart ssh
  when: first5ssh_manageconfig | bool
